### ISSUE TITLE
Opposites, leave and ng-repeat animations not working

### ISSUE THREAD

**Issue by sharpmachine** [cgwyllie/angular-velocity#30]
Hey there. The only thing I can get to work in just plain old `velocity-transition-whatever` on `<div ui-view></div>`.

I can't get `velocity-opposites-transition-whatever` or `velocity-leave-transition-whatever` to work, and I can't get it to work on `ng-repeat` at all.

What am I doing wrong? I'm using UI-Router...does that cause issues?

**Comment by sharpmachine** [comment]
Turns out I was missing this CSS:

``` css
   <style type="text/css">
    /* A parent element to allow views to overlap as animated */
    .view-container {
        position: relative;
    }
    /* Make sure that ng-view is absolutely positioned in parent */
    [ng-view] {
        position: absolute;
        width: 100%;
    }
    /* Specify z-index to make the entering view on top of the leaving one */
    [ng-view].ng-leave {
        z-index: 0;
    }
    [ng-view].ng-enter {
        z-index: 1;
    }
    </style>
```

I feel like that should have been in the documentation.
